name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set executable permissions for scripts
      run: chmod +x bin/*
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cdklein/kegserve:latest
    - name: Push image to docker hub
      run: |
        docker login --username cdklein --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push cdklein/kegserve:latest


        
